@startuml
left to right direction
skinparam packageStyle rectangle

actor "Estudiante" as estudiante
actor "Administrador" as admin

rectangle "Sistema de Reservas de Salas" {
  usecase "Reservar Sala" as UC1
  usecase "Filtrar Salas" as UC2
  usecase "Ver Reservas" as UC3
  usecase "Cancelar Reserva" as UC4
  usecase "Gestionar Salas" as UC5
  
  UC1 .> UC2 : <<extends>>
}

estudiante --> UC1
estudiante --> UC3
estudiante --> UC4

admin --> UC5

@enduml
